#!/bin/bash
GOOS=darwin GOARCH=arm64 CGO_ENABLED=0 go build -trimpath -ldflags="-buildid=" -o vecbackup-darwin-arm64 ./cmd/vecbackup
GOOS=darwin GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags="-buildid=" -o vecbackup-darwin-amd64 ./cmd/vecbackup
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags="-buildid=" -o vecbackup-linux-amd64 ./cmd/vecbackup
GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags="-buildid=" -o vecbackup-windows-amd64.exe ./cmd/vecbackup
